### ISSUE TITLE
"java.util.ConcurrentModificationException" occurs periodically

### ISSUE THREAD

**Issue by nuransan** [igr/idea-sexyeditor#24]
```
java.util.ConcurrentModificationException
	at java.util.WeakHashMap$HashIterator.nextEntry(WeakHashMap.java:806)
	at java.util.WeakHashMap$KeyIterator.next(WeakHashMap.java:839)
	at net.intellij.plugins.sexyeditor.BackgroundConfiguration.lambda$createThread$0(BackgroundConfiguration.java:290)
	at java.lang.Thread.run(Thread.java:745)
```
Sexy Editor Version: 2.1

IntelliJ IDEA 2018.2 (Community Edition)
Build #IC-182.3684.101, built on July 24, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.9.0-3-amd64

**Comment by igr** [comment]
Closing this one as the weak hashmap is removed.
